name: PerfIO CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 21
          - os: ubuntu-latest
            java: 23
          - os: macos-latest
            java: 23
    runs-on: ${{matrix.os}}
    name: Test
    steps:
    - uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: 'sbt'
    - name: Set up sbt
      uses: sbt/setup-sbt@v1
    - name: Set up protobuf
      run: |
        mkdir ~/protobuf
        if [[ "$RUNNER_OS" = "macOS" ]]; then
          PB_URL=https://github.com/protocolbuffers/protobuf/releases/download/v29.0-rc3/protoc-29.0-rc-3-osx-aarch_64.zip
        else
          PB_URL=https://github.com/protocolbuffers/protobuf/releases/download/v29.0-rc3/protoc-29.0-rc-3-linux-x86_64.zip
        fi
        (cd ~/protobuf && curl -Lo pb.zip $PB_URL && unzip pb.zip)
    - name: Run tests
      run: |
        if [[ "${{ matrix.java }}" = "21" ]]; then
          export JAVA_OPTS=--enable-preview
        fi
        sbt test bootstrapProto proto/test
    - name: Build javadoc
      if: matrix.java == 23
      run: |
        sbt core/doc

  integration:
    runs-on: ubuntu-latest
    name: Multi-Release JAR Integration Test
    steps:
    - uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: |
          21
          22
        distribution: 'temurin'
        cache: 'sbt'
    - name: Set up sbt
      uses: sbt/setup-sbt@v1
    - name: Run tests
      run: |
        # Build multi-release override classes on Java 22
        PATH=$JAVA_HOME_22_X64/bin:$PATH JAVA_HOME=$JAVA_HOME_22_X64 sbt \
          core/compile
        cp -r core/target/classes override-core-j22
        # Build jar on Java 21 with --enable-preview and include Java 22 overrides
        PATH=$JAVA_HOME_21_X64/bin:$PATH JAVA_HOME=$JAVA_HOME_21_X64 JAVA_OPTS=--enable-preview \
          OVERRIDE_CORE_J22=`realpath override-core-j22` sbt \
          core/clean \
          core/packageBin
        # Run tests with multi-release jar
        cp `realpath core/target/perfio-*.jar` override-test.jar
        PATH=$JAVA_HOME_21_X64/bin:$PATH JAVA_HOME=$JAVA_HOME_21_X64 JAVA_OPTS=--enable-preview \
          OVERRIDE_TEST_JAR=`realpath override-test.jar` sbt \
          test/test
        PATH=$JAVA_HOME_22_X64/bin:$PATH JAVA_HOME=$JAVA_HOME_22_X64 \
          OVERRIDE_TEST_JAR=`realpath override-test.jar` sbt \
          test/test
